import type { ExperiencePack, Option } from "@/lib/thin-path/types";
import { LEX } from "./lexicon";

function clip(id: keyof typeof LEX, label: string): Option {
  const lex = LEX[id];
  return {
    id,
    label,
    layer: lex.layer,
    prior: lex.prior,
    keys: lex.keys,
    poster: `/media/${id}.jpg?v=31`,
    video: `/media/${id}.mp4?v=31`,
    videoHevc: `/media/${id}.hevc.mp4?v=31`,
  };
}

/**
 * 今夜의 한 팩. 질문 3개만. 향·맛·입안이라는 말은 화면에 안 낸다.
 * 사람은 일본어 형용사만 고른다. 분위기는 지정 영상(릴스)이 전달한다.
 * はじまり → さかり → なごり : 한 잔의 시작·피크·끝.
 * 선택지 위→아래 순서 = 논문 총출현(prior). まろやかな는 copy에서만 센다.
 */
export const tonight: ExperiencePack = {
  id: "tonight",
  phases: ["はじまり", "さかり", "なごり"],
  intro: {
    lines: [
      { text: "How many" },
      { text: "drinks", emphasis: true },
      { text: "are too many" },
      { text: "drinks?" },
    ],
    start: "スタート",
  },
  questions: [
    {
      id: "aroma",
      phase: "はじまり",
      prompt: "心の向くまま歩くなら、\nどんな道？",
      confirm: "今夜は、これで。",
      options: [
        clip("aroma_fruity", "フルーティーな"),
        clip("aroma_hoppy", "ホップの"),
        clip("aroma_fresh", "爽やかな"),
        clip("aroma_malty", "モルトの"),
        clip("aroma_floral", "華やかな"),
      ],
    },
    {
      id: "taste",
      phase: "さかり",
      prompt: "ひと休みするなら、\nどんな一杯？",
      confirm: "一口は、これで。",
      options: [clip("taste_sweet", "ほのかな甘み"), clip("taste_bitter", "ほろ苦い")],
    },
    {
      id: "body",
      phase: "なごり",
      prompt: "帰り道、\nどんな音楽に包まれたい？",
      confirm: "帰り道は、これで。",
      options: [
        clip("body_smooth", "なめらかな"),
        clip("body_soft", "柔らかな"),
        clip("body_gentle", "優しい"),
        clip("body_thin", "爽やかな"),
        clip("body_full", "まろやかな"),
      ],
    },
  ],
  items: [
    {
      id: "heiwa-red-ale",
      name: "平和クラフト レッドエール",
      style: "RED ALE",
      abv: "5.0%",
      maker: "平和酒造",
      place: "WAKAYAMA",
      line: "麦芽のキャラメル感と、赤ワインのようなアロマ。",
      copy: "「麦芽とホップのみを使って」赤いビールを作りました。フルーツやその他の原料は使っていません。焙煎したモルトは使用せず高温で乾燥させる「焙炒」したモルトを全量使用しているため、麦芽のキャラメル感とともに少し赤ワインのようなアロマが特徴です。またボディもミディアム程度でテーブルビールとして飲み飽きしない味わいとなっています。洋だとレバーペーストなど少し血のニュアンスのある食材、和だと醤油やみりんを使った味わいのものがお勧めです。またレッドエールは、ビールのオリンピックとも呼ばれる、世界で最も権威のあるビール競技会「ワールド・ビア・カップ」にて、 2022年にIRISH-STYLE RED ALE部門で金賞を受賞しました。世界一に輝いたビールをぜひお楽しみください。",
      source: {
        kind: "ビール",
        ingredients: "麦芽・ホップ",
        shelf: "出荷日から5ヶ月",
        text: "「麦芽とホップのみを使って」赤いビールを作りました。フルーツやその他の原料は使っていません。焙煎したモルトは使用せず高温で乾燥させる「焙炒」したモルトを全量使用しているため、麦芽のキャラメル感とともに少し赤ワインのようなアロマが特徴です。またボディもミディアム程度でテーブルビールとして飲み飽きしない味わいとなっています。洋だとレバーペーストなど少し血のニュアンスのある食材、和だと醤油やみりんを使った味わいのものがお勧めです。またレッドエールは、ビールのオリンピックとも呼ばれる、世界で最も権威のあるビール競技会「ワールド・ビア・カップ」にて、 2022年にIRISH-STYLE RED ALE部門で金賞を受賞しました。世界一に輝いたビールをぜひお楽しみください。",
      },
      bottle: "tall",
      art: "/beers/heiwa-red-ale.png?v=3",
      booth: "4-2",
      poster: { filename: "平和クラフトレッドエール.png" },
    },
    {
      id: "heiwa-white-ale",
      name: "平和クラフト ホワイトエール",
      style: "WHITE ALE",
      abv: "5.0%",
      maker: "平和酒造",
      place: "WAKAYAMA",
      line: "ふわっとオレンジの香り、小麦の柔らかさ。",
      copy: "ベースはベルジャン、イーストとホップがアメリカンなウィートエールです。 苦味は少し抑えめで小麦由来の柔らかさがあります。ふわっとオレンジの香りがしてビールが苦手な方にもおすすめ。 隠し味に和歌山県産の柚子ピールも効かせて爽やかな仕上がりになっています｡ お魚料理､野菜料理におすすめです｡",
      source: {
        kind: "ビール",
        ingredients: "麦芽・ホップ・オレンジピール・コリアンダー・柚子ピール",
        shelf: "出荷日から5ヶ月",
        text: "ベースはベルジャン、イーストとホップがアメリカンなウィートエールです。 苦味は少し抑えめで小麦由来の柔らかさがあります。ふわっとオレンジの香りがしてビールが苦手な方にもおすすめ。 隠し味に和歌山県産の柚子ピールも効かせて爽やかな仕上がりになっています｡ お魚料理､野菜料理におすすめです｡",
      },
      bottle: "tall",
      art: "/beers/heiwa-white-ale.png?v=3",
      booth: "4-2",
      poster: { filename: "平和クラフトホワイトエール.png" },
    },
    {
      id: "heiwa-pale-ale",
      name: "平和クラフト ペールエール",
      style: "PALE ALE",
      abv: "5.0%",
      maker: "平和酒造",
      place: "WAKAYAMA",
      line: "爽やかなホップの香り、落ち着いて飲める一杯。",
      copy: "オーソドックスなモルト・ホップ・イーストを用いた王道的なペールエールです。 爽やかなホップの香りもありながら、落ち着いて飲める1杯を目指しました。 お肉料理やアメリカンフードに合わせて、しっかり冷やしてお楽しみください。",
      source: {
        kind: "ビール",
        ingredients: "麦芽・ホップ",
        shelf: "出荷日から5ヶ月",
        text: "オーソドックスなモルト・ホップ・イーストを用いた王道的なペールエールです。 爽やかなホップの香りもありながら、落ち着いて飲める1杯を目指しました。 お肉料理やアメリカンフードに合わせて、しっかり冷やしてお楽しみください。",
      },
      bottle: "tall",
      art: "/beers/heiwa-pale-ale.png?v=3",
      booth: "4-2",
      poster: { filename: "平和クラフトペールエール.png" },
    },
    {
      id: "rydeen-weizen",
      name: "ライディーンビール ヴァイツェン",
      style: "WEIZEN",
      abv: "5.0%",
      maker: "猿倉山ビール醸造所",
      place: "MINAMIUONUMA",
      line: "フルーティーな香りと、柔らかな酸味。",
      copy: "フルーティーな香りと柔らかな酸味。たくさんの酵母がいきています。小麦麦芽特有のほのかな酸味とやわらかな香りが口いっぱいに広がり、苦味の少ないやさしい味わいです。",
      source: {
        kind: "ビール",
        ingredients: "麦芽・ホップ",
        text: "フルーティーな香りと柔らかな酸味 たくさんの酵母がいきています。小麦麦芽特有のほのかな酸味とやわらかな香りが口いっぱいに広がり、苦味の少ないやさしい味わいです。",
      },
      bottle: "tall",
      art: "/beers/rydeen-weizen.png?v=3",
      booth: "4-2",
      poster: { filename: "ライディーンヴァイツェン.png" },
    },
    {
      id: "rydeen-alt",
      name: "ライディーンビール アルト",
      style: "ALT",
      abv: "5.0%",
      maker: "猿倉山ビール醸造所",
      place: "MINAMIUONUMA",
      line: "香ばしい香りとコク、ホップのすっきりした苦味。",
      copy: "コクのある中にもすっきりとした味わいに仕上がっています。濃色麦芽が醸し出す香ばしい香りやコク、ほのかに感じる甘みとホップのすっきりとした苦味が特徴のビールです。",
      source: {
        kind: "ビール",
        ingredients: "麦芽・ホップ",
        text: "コクのある中にもすっきりとした味わいに仕上がっています。濃色麦芽が醸し出す香ばしい香りやコク、ほのかに感じる甘みとホップのすっきりとした苦味が特徴のビールです。",
      },
      bottle: "stout",
      art: "/beers/rydeen-alt.png?v=3",
      booth: "4-2",
      poster: { filename: "ライディーンアルト.png" },
    },
    {
      id: "rydeen-ipa",
      name: "ライディーンビール IPA",
      style: "IPA",
      abv: "6.0%",
      maker: "猿倉山ビール醸造所",
      place: "MINAMIUONUMA",
      line: "ホップの切れのよい苦味と、柑橘の香り。",
      copy: "ホップの青々とした切れのよい苦味と柑橘系の豊かな香り。麦芽を贅沢に使用し、豊かなモルトの風味と華やかな香りが楽しめます。",
      source: {
        kind: "ビール",
        ingredients: "麦芽・ホップ",
        text: "ホップの青々とした切れのよい苦味と柑橘系の豊かな香り。麦芽を贅沢に使用し、豊かなモルトの風味と華やかな香りが楽しめます。",
      },
      bottle: "tall",
      art: "/beers/rydeen-ipa.png?v=3",
      booth: "4-2",
      poster: { filename: "ライディーンIPA.png" },
    },
    {
      id: "rydeen-pilsner",
      name: "ライディーンビール ピルスナー",
      style: "PILSNER",
      abv: "5.0%",
      maker: "猿倉山ビール醸造所",
      place: "MINAMIUONUMA",
      line: "麦芽の香りとホップの苦味、クリアな喉越し。",
      copy: "低温で長期熟成、麦芽の香りとホップの苦味、コクのある味わい。豊かなモルトの風味とさわやかな苦味、クリアな喉越しが特徴です。",
      source: {
        kind: "ビール",
        ingredients: "麦芽・ホップ",
        text: "低温で長期熟成、麦芽の香りとホップの苦味、コクのある味わい。豊かなモルトの風味とさわやかな苦味、クリアな喉越しが特徴です。",
      },
      bottle: "tall",
      art: "/beers/rydeen-pilsner.png?v=3",
      booth: "4-2",
      poster: { filename: "ライディーンピルスナー.png" },
    },
  ],
};
